name: Update Version Record

on:
  repository_dispatch:
    types: [version_update]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update Files
        run: |
          # Decode and overwrite README.md
          echo "${{ github.event.client_payload.readme }}" | base64 -d > README.md
          
          # Decode Release Note and store in multi-line environment variable
          echo "DECODED_NOTES<<EOF" >> $GITHUB_ENV
          echo "${{ github.event.client_payload.release_note }}" | base64 -d >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add VERSION.txt
          git commit -m "Update to version ${{ github.event.client_payload.version }}"
          git push

      - name: Create Public Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.client_payload.version }}
          name: Release ${{ github.event.client_payload.version }}
          body: |
            ### 🚀 Automatically updated from private repository
            
            ${{ env.DECODED_NOTES }}
            
            ---
            *Sync Date: $(date +'%Y-%m-%d %H:%M')*